--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4 (Debian 17.4-1.pgdg120+2)
-- Dumped by pg_dump version 17.4 (Debian 17.4-1.pgdg120+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: timeseries_impedancetestdata; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.timeseries_impedancetestdata (
    id bigint NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    real_impedance numeric(10,5) NOT NULL,
    imaginary_impedance numeric(10,5) NOT NULL,
    batch_id bigint NOT NULL,
    cell_id bigint NOT NULL,
    type_id bigint NOT NULL
);


ALTER TABLE public.timeseries_impedancetestdata OWNER TO postgres;

--
-- Name: timeseries_impedancetestdata_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.timeseries_impedancetestdata ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.timeseries_impedancetestdata_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: timeseries_potentiostatictestdata; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.timeseries_potentiostatictestdata (
    id bigint NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    voltage numeric(10,5) NOT NULL,
    "time" numeric(10,5) NOT NULL,
    current_density numeric(10,5) NOT NULL,
    batch_id bigint NOT NULL,
    cell_id bigint NOT NULL,
    type_id bigint NOT NULL
);


ALTER TABLE public.timeseries_potentiostatictestdata OWNER TO postgres;

--
-- Name: timeseries_potentiostatictestdata_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.timeseries_potentiostatictestdata ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.timeseries_potentiostatictestdata_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: timeseries_pwmtestdata; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.timeseries_pwmtestdata (
    id bigint NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    "time" numeric(10,5) NOT NULL,
    current_density numeric(10,5) NOT NULL,
    batch_id bigint NOT NULL,
    cell_id bigint NOT NULL,
    type_id bigint NOT NULL
);


ALTER TABLE public.timeseries_pwmtestdata OWNER TO postgres;

--
-- Name: timeseries_pwmtestdata_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.timeseries_pwmtestdata ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.timeseries_pwmtestdata_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: warehouse_batch; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.warehouse_batch (
    id bigint NOT NULL,
    name character varying(25) NOT NULL
);


ALTER TABLE public.warehouse_batch OWNER TO postgres;

--
-- Name: warehouse_batch_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.warehouse_batch ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.warehouse_batch_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: warehouse_category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.warehouse_category (
    id bigint NOT NULL,
    name character varying(25) NOT NULL
);


ALTER TABLE public.warehouse_category OWNER TO postgres;

--
-- Name: warehouse_category_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.warehouse_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.warehouse_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: warehouse_cell; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.warehouse_cell (
    id bigint NOT NULL,
    name character varying(25) NOT NULL,
    batch_id bigint NOT NULL
);


ALTER TABLE public.warehouse_cell OWNER TO postgres;

--
-- Name: warehouse_cell_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.warehouse_cell ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.warehouse_cell_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: warehouse_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.warehouse_type (
    id bigint NOT NULL,
    name character varying(25) NOT NULL,
    category_id bigint NOT NULL
);


ALTER TABLE public.warehouse_type OWNER TO postgres;

--
-- Name: warehouse_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.warehouse_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.warehouse_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add batch	5	add_batch
18	Can change batch	5	change_batch
19	Can delete batch	5	delete_batch
20	Can view batch	5	view_batch
21	Can add category	6	add_category
22	Can change category	6	change_category
23	Can delete category	6	delete_category
24	Can view category	6	view_category
25	Can add cell	7	add_cell
26	Can change cell	7	change_cell
27	Can delete cell	7	delete_cell
28	Can view cell	7	view_cell
29	Can add type	8	add_type
30	Can change type	8	change_type
31	Can delete type	8	delete_type
32	Can view type	8	view_type
33	Can add impedance test data	9	add_impedancetestdata
34	Can change impedance test data	9	change_impedancetestdata
35	Can delete impedance test data	9	delete_impedancetestdata
36	Can view impedance test data	9	view_impedancetestdata
37	Can add potentiostatic test data	10	add_potentiostatictestdata
38	Can change potentiostatic test data	10	change_potentiostatictestdata
39	Can delete potentiostatic test data	10	delete_potentiostatictestdata
40	Can view potentiostatic test data	10	view_potentiostatictestdata
41	Can add pwm testdata	11	add_pwmtestdata
42	Can change pwm testdata	11	change_pwmtestdata
43	Can delete pwm testdata	11	delete_pwmtestdata
44	Can view pwm testdata	11	view_pwmtestdata
45	Can add content type	12	add_contenttype
46	Can change content type	12	change_contenttype
47	Can delete content type	12	delete_contenttype
48	Can view content type	12	view_contenttype
49	Can add session	13	add_session
50	Can change session	13	change_session
51	Can delete session	13	delete_session
52	Can view session	13	view_session
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$1000000$cfQbyHIBc48ek5lVORoXXv$xpAPYEcuKec4mpvb8xGwuttV1A/N0FkHEEG/z3GVpq4=	2025-04-10 19:14:56+00	t	nathan	Nathan	Woodruff	nathan.woodruff@inl.gov	t	t	2025-04-10 19:14:44+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2025-04-10 19:15:30.000439+00	1	Characterization	1	[{"added": {}}]	6	1
2	2025-04-10 19:15:33.65029+00	2	Durability	1	[{"added": {}}]	6	1
3	2025-04-10 19:15:37.562747+00	3	Performance	1	[{"added": {}}]	6	1
4	2025-04-10 19:15:51.413888+00	1	Characterization: Impedance	1	[{"added": {}}]	8	1
5	2025-04-10 19:16:08.363098+00	2	Durability: Pulse Width Modulation	1	[{"added": {}}]	8	1
6	2025-04-10 19:16:19.400845+00	3	Performance: Potentiostatic	1	[{"added": {}}]	8	1
7	2025-04-10 19:16:43.254321+00	1	1-14-22-3A	1	[{"added": {}}]	5	1
8	2025-04-10 19:16:48.588324+00	2	4-12-22-2A	1	[{"added": {}}]	5	1
9	2025-04-10 19:16:53.629906+00	3	5-11-22-5A	1	[{"added": {}}]	5	1
10	2025-04-10 19:16:58.941407+00	4	2-4-22-2A	1	[{"added": {}}]	5	1
11	2025-04-10 19:17:18.805989+00	1	1-14-22-3A: BC-7	1	[{"added": {}}]	7	1
12	2025-04-10 19:17:25.284265+00	2	1-14-22-3A: BC-10	1	[{"added": {}}]	7	1
13	2025-04-10 19:17:32.904314+00	3	4-12-22-2A: BC-9	1	[{"added": {}}]	7	1
14	2025-04-10 19:17:39.464222+00	4	4-12-22-2A: BC-12	1	[{"added": {}}]	7	1
15	2025-04-10 19:17:47.920271+00	5	5-11-22-5A: BC-16	1	[{"added": {}}]	7	1
16	2025-04-10 19:17:53.612157+00	6	5-11-22-5A: BC-3	1	[{"added": {}}]	7	1
17	2025-04-10 19:17:58.187101+00	7	5-11-22-5A: BC-7	1	[{"added": {}}]	7	1
18	2025-04-10 19:18:05.705094+00	8	2-4-22-2A: BC-2	1	[{"added": {}}]	7	1
19	2025-04-10 19:18:11.146906+00	9	2-4-22-2A: BC-6	1	[{"added": {}}]	7	1
20	2025-04-10 19:18:16.228786+00	10	2-4-22-2A: BC-9	1	[{"added": {}}]	7	1
21	2025-04-10 19:18:22.330696+00	11	2-4-22-2A: BC-20	1	[{"added": {}}]	7	1
22	2025-04-10 19:18:28.160894+00	12	2-4-22-2A: BC-34	1	[{"added": {}}]	7	1
23	2025-04-10 19:18:34.433785+00	13	2-4-22-2A: BC-36	1	[{"added": {}}]	7	1
24	2025-04-10 19:20:32.10908+00	14	2-4-22-2A: BC-18	1	[{"added": {}}]	7	1
25	2025-04-10 19:20:36.971695+00	15	2-4-22-2A: BC-33	1	[{"added": {}}]	7	1
26	2025-04-10 19:21:32.256555+00	1	nathan	2	[{"changed": {"fields": ["First name", "Last name", "Email address"]}}]	4	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	warehouse	batch
6	warehouse	category
7	warehouse	cell
8	warehouse	type
9	timeseries	impedancetestdata
10	timeseries	potentiostatictestdata
11	timeseries	pwmtestdata
12	contenttypes	contenttype
13	sessions	session
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-04-10 19:13:09.364557+00
2	auth	0001_initial	2025-04-10 19:13:09.39633+00
3	admin	0001_initial	2025-04-10 19:13:09.407772+00
4	admin	0002_logentry_remove_auto_add	2025-04-10 19:13:09.41397+00
5	admin	0003_logentry_add_action_flag_choices	2025-04-10 19:13:09.421344+00
6	contenttypes	0002_remove_content_type_name	2025-04-10 19:13:09.432806+00
7	auth	0002_alter_permission_name_max_length	2025-04-10 19:13:09.439229+00
8	auth	0003_alter_user_email_max_length	2025-04-10 19:13:09.446013+00
9	auth	0004_alter_user_username_opts	2025-04-10 19:13:09.451787+00
10	auth	0005_alter_user_last_login_null	2025-04-10 19:13:09.45858+00
11	auth	0006_require_contenttypes_0002	2025-04-10 19:13:09.460684+00
12	auth	0007_alter_validators_add_error_messages	2025-04-10 19:13:09.466483+00
13	auth	0008_alter_user_username_max_length	2025-04-10 19:13:09.474763+00
14	auth	0009_alter_user_last_name_max_length	2025-04-10 19:13:09.483232+00
15	auth	0010_alter_group_name_max_length	2025-04-10 19:13:09.490012+00
16	auth	0011_update_proxy_permissions	2025-04-10 19:13:09.49467+00
17	auth	0012_alter_user_first_name_max_length	2025-04-10 19:13:09.501975+00
18	sessions	0001_initial	2025-04-10 19:13:09.508891+00
19	warehouse	0001_initial	2025-04-10 19:13:09.526652+00
20	timeseries	0001_initial	2025-04-10 19:13:09.557531+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
cze7govdzkh8f599svhlbqvgf1o2uyo6	.eJxVjL0OwiAURt-F2RB-Czi6-wzkXi5I1dCktJPx3ZWkgy7f8J2T82IR9q3Gvec1zsTOTLLT74eQHrkNQHdot4WnpW3rjHwo_KCdXxfKz8vh_gUq9DqyQk2mkC3gfUDnFBKRE1prDDLlySMakN8xATMVm6TNVhjSJoESCtj7A-xUOEs:1u2xMW:kuuO5nW5wxUSt0mlQWkfIpXWMwuJNnr-edf3dkkAA0o	2025-04-24 19:14:56.761564+00
\.


--
-- Data for Name: timeseries_impedancetestdata; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.timeseries_impedancetestdata (id, "timestamp", real_impedance, imaginary_impedance, batch_id, cell_id, type_id) FROM stdin;
\.


--
-- Data for Name: timeseries_potentiostatictestdata; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.timeseries_potentiostatictestdata (id, "timestamp", voltage, "time", current_density, batch_id, cell_id, type_id) FROM stdin;
\.


--
-- Data for Name: timeseries_pwmtestdata; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.timeseries_pwmtestdata (id, "timestamp", "time", current_density, batch_id, cell_id, type_id) FROM stdin;
\.


--
-- Data for Name: warehouse_batch; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.warehouse_batch (id, name) FROM stdin;
1	1-14-22-3A
2	4-12-22-2A
3	5-11-22-5A
4	2-4-22-2A
\.


--
-- Data for Name: warehouse_category; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.warehouse_category (id, name) FROM stdin;
1	Characterization
2	Durability
3	Performance
\.


--
-- Data for Name: warehouse_cell; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.warehouse_cell (id, name, batch_id) FROM stdin;
1	BC-7	1
2	BC-10	1
3	BC-9	2
4	BC-12	2
5	BC-16	3
6	BC-3	3
7	BC-7	3
8	BC-2	4
9	BC-6	4
10	BC-9	4
11	BC-20	4
12	BC-34	4
13	BC-36	4
14	BC-18	4
15	BC-33	4
\.


--
-- Data for Name: warehouse_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.warehouse_type (id, name, category_id) FROM stdin;
1	Impedance	1
2	Pulse Width Modulation	2
3	Potentiostatic	3
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 52, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 26, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 13, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 20, true);


--
-- Name: timeseries_impedancetestdata_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.timeseries_impedancetestdata_id_seq', 1, false);


--
-- Name: timeseries_potentiostatictestdata_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.timeseries_potentiostatictestdata_id_seq', 1, false);


--
-- Name: timeseries_pwmtestdata_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.timeseries_pwmtestdata_id_seq', 1, false);


--
-- Name: warehouse_batch_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.warehouse_batch_id_seq', 4, true);


--
-- Name: warehouse_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.warehouse_category_id_seq', 3, true);


--
-- Name: warehouse_cell_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.warehouse_cell_id_seq', 15, true);


--
-- Name: warehouse_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.warehouse_type_id_seq', 3, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: timeseries_impedancetestdata timeseries_impedancetestdata_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.timeseries_impedancetestdata
    ADD CONSTRAINT timeseries_impedancetestdata_pkey PRIMARY KEY (id);


--
-- Name: timeseries_potentiostatictestdata timeseries_potentiostatictestdata_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.timeseries_potentiostatictestdata
    ADD CONSTRAINT timeseries_potentiostatictestdata_pkey PRIMARY KEY (id);


--
-- Name: timeseries_pwmtestdata timeseries_pwmtestdata_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.timeseries_pwmtestdata
    ADD CONSTRAINT timeseries_pwmtestdata_pkey PRIMARY KEY (id);


--
-- Name: warehouse_batch warehouse_batch_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.warehouse_batch
    ADD CONSTRAINT warehouse_batch_name_key UNIQUE (name);


--
-- Name: warehouse_batch warehouse_batch_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.warehouse_batch
    ADD CONSTRAINT warehouse_batch_pkey PRIMARY KEY (id);


--
-- Name: warehouse_category warehouse_category_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.warehouse_category
    ADD CONSTRAINT warehouse_category_name_key UNIQUE (name);


--
-- Name: warehouse_category warehouse_category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.warehouse_category
    ADD CONSTRAINT warehouse_category_pkey PRIMARY KEY (id);


--
-- Name: warehouse_cell warehouse_cell_batch_id_name_8210a35b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.warehouse_cell
    ADD CONSTRAINT warehouse_cell_batch_id_name_8210a35b_uniq UNIQUE (batch_id, name);


--
-- Name: warehouse_cell warehouse_cell_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.warehouse_cell
    ADD CONSTRAINT warehouse_cell_pkey PRIMARY KEY (id);


--
-- Name: warehouse_type warehouse_type_category_id_name_80b18f67_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.warehouse_type
    ADD CONSTRAINT warehouse_type_category_id_name_80b18f67_uniq UNIQUE (category_id, name);


--
-- Name: warehouse_type warehouse_type_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.warehouse_type
    ADD CONSTRAINT warehouse_type_name_key UNIQUE (name);


--
-- Name: warehouse_type warehouse_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.warehouse_type
    ADD CONSTRAINT warehouse_type_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: timeseries__batch_i_0a3bfa_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX timeseries__batch_i_0a3bfa_idx ON public.timeseries_pwmtestdata USING btree (batch_id, cell_id);


--
-- Name: timeseries__batch_i_5d9305_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX timeseries__batch_i_5d9305_idx ON public.timeseries_potentiostatictestdata USING btree (batch_id, cell_id);


--
-- Name: timeseries__batch_i_dfa3ea_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX timeseries__batch_i_dfa3ea_idx ON public.timeseries_impedancetestdata USING btree (batch_id, cell_id);


--
-- Name: timeseries_impedancetestdata_batch_id_8383d642; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX timeseries_impedancetestdata_batch_id_8383d642 ON public.timeseries_impedancetestdata USING btree (batch_id);


--
-- Name: timeseries_impedancetestdata_cell_id_84255de6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX timeseries_impedancetestdata_cell_id_84255de6 ON public.timeseries_impedancetestdata USING btree (cell_id);


--
-- Name: timeseries_impedancetestdata_type_id_48e9e8d6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX timeseries_impedancetestdata_type_id_48e9e8d6 ON public.timeseries_impedancetestdata USING btree (type_id);


--
-- Name: timeseries_potentiostatictestdata_batch_id_396a0010; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX timeseries_potentiostatictestdata_batch_id_396a0010 ON public.timeseries_potentiostatictestdata USING btree (batch_id);


--
-- Name: timeseries_potentiostatictestdata_cell_id_6532edb1; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX timeseries_potentiostatictestdata_cell_id_6532edb1 ON public.timeseries_potentiostatictestdata USING btree (cell_id);


--
-- Name: timeseries_potentiostatictestdata_type_id_ed14eb81; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX timeseries_potentiostatictestdata_type_id_ed14eb81 ON public.timeseries_potentiostatictestdata USING btree (type_id);


--
-- Name: timeseries_pwmtestdata_batch_id_33dd7584; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX timeseries_pwmtestdata_batch_id_33dd7584 ON public.timeseries_pwmtestdata USING btree (batch_id);


--
-- Name: timeseries_pwmtestdata_cell_id_e211cf94; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX timeseries_pwmtestdata_cell_id_e211cf94 ON public.timeseries_pwmtestdata USING btree (cell_id);


--
-- Name: timeseries_pwmtestdata_type_id_97926072; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX timeseries_pwmtestdata_type_id_97926072 ON public.timeseries_pwmtestdata USING btree (type_id);


--
-- Name: warehouse_batch_name_ad71496c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX warehouse_batch_name_ad71496c_like ON public.warehouse_batch USING btree (name varchar_pattern_ops);


--
-- Name: warehouse_category_name_d4930ca6_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX warehouse_category_name_d4930ca6_like ON public.warehouse_category USING btree (name varchar_pattern_ops);


--
-- Name: warehouse_cell_batch_id_dba556f4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX warehouse_cell_batch_id_dba556f4 ON public.warehouse_cell USING btree (batch_id);


--
-- Name: warehouse_type_category_id_029400cd; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX warehouse_type_category_id_029400cd ON public.warehouse_type USING btree (category_id);


--
-- Name: warehouse_type_name_df317834_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX warehouse_type_name_df317834_like ON public.warehouse_type USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: timeseries_impedancetestdata timeseries_impedance_batch_id_8383d642_fk_warehouse; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.timeseries_impedancetestdata
    ADD CONSTRAINT timeseries_impedance_batch_id_8383d642_fk_warehouse FOREIGN KEY (batch_id) REFERENCES public.warehouse_batch(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: timeseries_impedancetestdata timeseries_impedance_cell_id_84255de6_fk_warehouse; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.timeseries_impedancetestdata
    ADD CONSTRAINT timeseries_impedance_cell_id_84255de6_fk_warehouse FOREIGN KEY (cell_id) REFERENCES public.warehouse_cell(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: timeseries_impedancetestdata timeseries_impedance_type_id_48e9e8d6_fk_warehouse; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.timeseries_impedancetestdata
    ADD CONSTRAINT timeseries_impedance_type_id_48e9e8d6_fk_warehouse FOREIGN KEY (type_id) REFERENCES public.warehouse_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: timeseries_potentiostatictestdata timeseries_potentios_batch_id_396a0010_fk_warehouse; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.timeseries_potentiostatictestdata
    ADD CONSTRAINT timeseries_potentios_batch_id_396a0010_fk_warehouse FOREIGN KEY (batch_id) REFERENCES public.warehouse_batch(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: timeseries_potentiostatictestdata timeseries_potentios_cell_id_6532edb1_fk_warehouse; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.timeseries_potentiostatictestdata
    ADD CONSTRAINT timeseries_potentios_cell_id_6532edb1_fk_warehouse FOREIGN KEY (cell_id) REFERENCES public.warehouse_cell(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: timeseries_potentiostatictestdata timeseries_potentios_type_id_ed14eb81_fk_warehouse; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.timeseries_potentiostatictestdata
    ADD CONSTRAINT timeseries_potentios_type_id_ed14eb81_fk_warehouse FOREIGN KEY (type_id) REFERENCES public.warehouse_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: timeseries_pwmtestdata timeseries_pwmtestdata_batch_id_33dd7584_fk_warehouse_batch_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.timeseries_pwmtestdata
    ADD CONSTRAINT timeseries_pwmtestdata_batch_id_33dd7584_fk_warehouse_batch_id FOREIGN KEY (batch_id) REFERENCES public.warehouse_batch(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: timeseries_pwmtestdata timeseries_pwmtestdata_cell_id_e211cf94_fk_warehouse_cell_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.timeseries_pwmtestdata
    ADD CONSTRAINT timeseries_pwmtestdata_cell_id_e211cf94_fk_warehouse_cell_id FOREIGN KEY (cell_id) REFERENCES public.warehouse_cell(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: timeseries_pwmtestdata timeseries_pwmtestdata_type_id_97926072_fk_warehouse_type_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.timeseries_pwmtestdata
    ADD CONSTRAINT timeseries_pwmtestdata_type_id_97926072_fk_warehouse_type_id FOREIGN KEY (type_id) REFERENCES public.warehouse_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: warehouse_cell warehouse_cell_batch_id_dba556f4_fk_warehouse_batch_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.warehouse_cell
    ADD CONSTRAINT warehouse_cell_batch_id_dba556f4_fk_warehouse_batch_id FOREIGN KEY (batch_id) REFERENCES public.warehouse_batch(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: warehouse_type warehouse_type_category_id_029400cd_fk_warehouse_category_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.warehouse_type
    ADD CONSTRAINT warehouse_type_category_id_029400cd_fk_warehouse_category_id FOREIGN KEY (category_id) REFERENCES public.warehouse_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

