services:
  faraday-app-service:
    build:
      context: ./app
      dockerfile: Dockerfiles/Dockerfile.prod.local
    ports:
      - "5173:80"
    depends_on:
      - faraday-server-service
  faraday-server-service:
    build:
      context: ./server
      dockerfile: Dockerfiles/Dockerfile.prod.local
    env_file:
      - ./server/server/.env.production
    entrypoint: ["bash", "./entrypoint.prod.sh"]
    ports:
      - "8000:8000"
      - "80:8000"
    depends_on:
      - faraday-db-service
  faraday-db-service:
    build:
      context: ./database
      dockerfile: Dockerfiles/Dockerfile.prod.local
    env_file:
      - ./database/.env.local
    ports:
      - "5432:5432"
  faraday-pgadmin-service:
    image: dpage/pgadmin4
    env_file:
      - ./database/.env.local
    ports:
      - "5050:80"
