FROM python:3.10

WORKDIR /usr/src/server

COPY . .

RUN pip install pip_system_certs --trusted-host files.pythonhosted.org --trusted-host pypi.org
RUN pip3 install -r requirements.txt
RUN pip3 install gunicorn

RUN chmod +x ./entrypoint.prod.sh
ENTRYPOINT /bin/bash ./entrypoint.prod.sh