FROM python:latest

# Configure INL certs and environment variables
RUN wget -q -P /usr/local/share/ca-certificates/ https://certstore.inl.gov/pki/CAINLROOT_B64.crt
RUN /usr/sbin/update-ca-certificates
ENV NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt
ENV REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
ENV CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
ENV SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
ENV SSL_CERT_DIR=/etc/ssl/certs/

WORKDIR  /usr/src/server

COPY . .
	
# Configure INL certs and environment variables
RUN pip config set global.trusted-host \
    "pypi.org files.pythonhosted.org pypi.python.org" \
    --trusted-host=pypi.python.org \
    --trusted-host=pypi.org \
    --trusted-host=files.pythonhosted.org

RUN pip install pip_system_certs --trusted-host files.pythonhosted.org --trusted-host pypi.org
RUN pip3 install -r requirements.txt
RUN pip3 install gunicorn

ENTRYPOINT ["/bin/bash", "./entrypoint.prod.sh"]