# Generated by Django 5.2 on 2025-04-17 19:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectrolysisCell',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.DecimalField(decimal_places=12, max_digits=255)),
                ('date', models.IntegerField()),
                ('provider', models.CharField(max_length=25)),
                ('test', models.CharField(max_length=25)),
                ('batch', models.CharField(max_length=25)),
                ('cell', models.CharField(max_length=25)),
                ('data', models.JSONField()),
                ('metadata', models.JSONField()),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'test', 'batch', 'cell'], name='timeseries__provide_aa6ac8_idx')],
            },
        ),
    ]
