# Generated by Django 5.2 on 2025-04-15 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0006_alter_relationship_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectrolysisCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DecimalField(decimal_places=12, max_digits=255)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=25)),
                ('leaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell_leaf', to='warehouse.node')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell', to='warehouse.ontology')),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell_root', to='warehouse.node')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ElectrolysisStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DecimalField(decimal_places=12, max_digits=255)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=25)),
                ('leaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stack_leaf', to='warehouse.node')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stack', to='warehouse.ontology')),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stack_root', to='warehouse.node')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
