# Generated by Django 5.2 on 2025-06-07 19:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeseries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectrolysisStack',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.BigIntegerField()),
                ('provider', models.CharField(max_length=25)),
                ('test', models.CharField(max_length=25)),
                ('stackid', models.CharField(max_length=25)),
                ('data', models.JSONField()),
                ('metadata', models.JSONField(null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'test', 'stackid'], name='timeseries__provide_290444_idx')],
            },
        ),
    ]
