# Generated by Django 5.2 on 2025-04-17 19:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeseries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electrolysiscell',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('36bc63fc-615f-4190-bcf2-e2d3ee929ab2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
