# Generated by Django 5.2 on 2025-04-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeseries', '0002_alter_electrolysiscell_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electrolysiscell',
            name='uuid',
            field=models.CharField(default='f8785cb4-5130-46ac-acbe-6bd61b336b06', editable=False, primary_key=True, serialize=False),
        ),
    ]
