# Generated by Django 5.2 on 2025-06-10 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeseries', '0002_electrolysisstack'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW electrolysisstacks_downsampled AS
            WITH time_buckets AS (
                SELECT
                    EXTRACT(EPOCH FROM date_trunc('hour', to_timestamp(ROUND((data->>'time')::numeric))))::BIGINT as bucket,
                    uuid,
                    date,
                    provider,
                    test,
                    stackid,
                    data,
                    metadata,
                    ROW_NUMBER() OVER (
                        PARTITION BY date_trunc('hour', to_timestamp(ROUND((data->>'time')::numeric))), provider, test, stackid
                        ORDER BY (data->>'time')::numeric
                    ) as row_number
                FROM timeseries_electrolysisstack
                WHERE data->>'time' IS NOT NULL
                    AND data->>'time' ~ '^-?[0-9]+\\.?[0-9]*$'
                    AND (data->>'time')::numeric > 0
            )
            SELECT uuid, date, provider, test, stackid, data, metadata, bucket
            FROM time_buckets
            WHERE row_number = 1
            ORDER BY bucket
            WITH NO DATA;
            """,
            reverse_sql="DROP MATERIALIZED VIEW IF EXISTS electrolysisstacks_downsampled;"
        ),
        migrations.RunSQL(
            """
            CREATE UNIQUE INDEX idx_electrolysisstacks_downsampled_unique ON electrolysisstacks_downsampled (uuid);
            CREATE INDEX idx_downsampled_view_compound ON electrolysisstacks_downsampled (provider, test, stackid);
            CREATE INDEX idx_downsampled_view_time ON electrolysisstacks_downsampled (bucket);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS idx_electrolysisstacks_downsampled_unique;
            DROP INDEX IF EXISTS idx_downsampled_view_compound;
            DROP INDEX IF EXISTS idx_downsampled_view_time;
            """
        )
    ]
