# Generated by Django 5.2 on 2025-04-17 19:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeseries', '0003_alter_electrolysiscell_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electrolysiscell',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('00713b98-b5f9-4d95-afe7-f46fe66d3643'), editable=False, primary_key=True, serialize=False),
        ),
    ]
