# Generated by Django 5.2 on 2025-04-17 20:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeseries', '0004_alter_electrolysiscell_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electrolysiscell',
            name='date',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='electrolysiscell',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
