# Generated by Django 5.2 on 2025-04-17 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeseries', '0005_alter_electrolysiscell_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electrolysiscell',
            name='time',
        ),
    ]
