# Generated by Django 5.2 on 2025-04-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeseries', '0006_remove_electrolysiscell_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electrolysiscell',
            name='metadata',
            field=models.JSONField(null=True),
        ),
    ]
