server {
  listen 80;
  gzip on;
  gzip_types application/octet-stream;
  gzip_proxied    no-cache no-store private expired auth;
  gzip_min_length 1000;
  client_max_body_size 5000M;

  location / {
    root /usr/share/nginx/html/;
    include /etc/nginx/mime.types;
    try_files $uri $uri/ /index.html;
    gzip_static on;
  }

  location /server/ {
    proxy_pass http://faraday-server-service;
    proxy_set_header Content-Type application/json;
  }
}