# Generated by Django 5.2 on 2025-04-08 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='faraday.batch')),
            ],
            options={
                'unique_together': {('batch', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='faraday.category')),
            ],
            options={
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PWMTestdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('time', models.DecimalField(decimal_places=5, max_digits=10)),
                ('current_density', models.DecimalField(decimal_places=5, max_digits=10)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faraday.batch')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faraday.cell')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faraday.type')),
            ],
            options={
                'indexes': [models.Index(fields=['batch', 'cell'], name='faraday_pwm_batch_i_462948_idx')],
            },
        ),
        migrations.CreateModel(
            name='PotentiostaticTestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('voltage', models.DecimalField(decimal_places=5, max_digits=10)),
                ('time', models.DecimalField(decimal_places=5, max_digits=10)),
                ('current_density', models.DecimalField(decimal_places=5, max_digits=10)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faraday.batch')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faraday.cell')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faraday.type')),
            ],
            options={
                'indexes': [models.Index(fields=['batch', 'cell'], name='faraday_pot_batch_i_c21039_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImpedanceTestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('real_impedance', models.DecimalField(decimal_places=5, max_digits=10)),
                ('imaginary_impedance', models.DecimalField(decimal_places=5, max_digits=10)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faraday.batch')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faraday.cell')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faraday.type')),
            ],
            options={
                'indexes': [models.Index(fields=['batch', 'cell'], name='faraday_imp_batch_i_935e0e_idx')],
            },
        ),
    ]
