--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4 (Debian 17.4-1.pgdg120+2)
-- Dumped by pg_dump version 17.4 (Debian 17.4-1.pgdg120+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: warehouse_class; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.warehouse_class (
    id bigint NOT NULL,
    name character varying(25) NOT NULL,
    description character varying(25) NOT NULL
);


ALTER TABLE public.warehouse_class OWNER TO postgres;

--
-- Name: warehouse_class_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.warehouse_class ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.warehouse_class_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: warehouse_node; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.warehouse_node (
    id bigint NOT NULL,
    name character varying(25) NOT NULL,
    cls_id bigint NOT NULL,
    ontology_id bigint NOT NULL
);


ALTER TABLE public.warehouse_node OWNER TO postgres;

--
-- Name: warehouse_node_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.warehouse_node ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.warehouse_node_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: warehouse_ontology; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.warehouse_ontology (
    id bigint NOT NULL,
    name character varying(25) NOT NULL
);


ALTER TABLE public.warehouse_ontology OWNER TO postgres;

--
-- Name: warehouse_ontology_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.warehouse_ontology ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.warehouse_ontology_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: warehouse_relationship; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.warehouse_relationship (
    id bigint NOT NULL,
    name character varying(25) NOT NULL,
    ontology_id bigint NOT NULL,
    source_id bigint NOT NULL,
    target_id bigint NOT NULL
);


ALTER TABLE public.warehouse_relationship OWNER TO postgres;

--
-- Name: warehouse_relationship_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.warehouse_relationship ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.warehouse_relationship_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1       Can add log entry       1       add_logentry
2       Can change log entry    1       change_logentry
3       Can delete log entry    1       delete_logentry
4       Can view log entry      1       view_logentry
5       Can add permission      2       add_permission
6       Can change permission   2       change_permission
7       Can delete permission   2       delete_permission
8       Can view permission     2       view_permission
9       Can add group   3       add_group
10      Can change group        3       change_group
11      Can delete group        3       delete_group
12      Can view group  3       view_group
13      Can add user    4       add_user
14      Can change user 4       change_user
15      Can delete user 4       delete_user
16      Can view user   4       view_user
17      Can add ontology        5       add_ontology
18      Can change ontology     5       change_ontology
19      Can delete ontology     5       delete_ontology
20      Can view ontology       5       view_ontology
21      Can add node    6       add_node
22      Can change node 6       change_node
23      Can delete node 6       delete_node
24      Can view node   6       view_node
25      Can add relationship    7       add_relationship
26      Can change relationship 7       change_relationship
27      Can delete relationship 7       delete_relationship
28      Can view relationship   7       view_relationship
29      Can add content type    8       add_contenttype
30      Can change content type 8       change_contenttype
31      Can delete content type 8       delete_contenttype
32      Can view content type   8       view_contenttype
33      Can add session 9       add_session
34      Can change session      9       change_session
35      Can delete session      9       delete_session
36      Can view session        9       view_session
37      Can add class   10      add_class
38      Can change class        10      change_class
39      Can delete class        10      delete_class
40      Can view class  10      view_class
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1       pbkdf2_sha256$1000000$e03zHD7dJVeRxwgozXTvYY$hwYm+YY7lLKKzixZpaIWoIINTSv8d5eru8XVTough54=       2025-04-11 22:29:25.461179+00  t       nathan                          t       t       2025-04-11 22:29:16.418144+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1       2025-04-11 22:29:32.885509+00   1       H2NEW   1       [{"added": {}}] 5       1
2       2025-04-11 22:33:23.745395+00   1       Class object (1)        1       [{"added": {}}] 10      1
3       2025-04-11 22:33:29.279935+00   2       Class object (2)        1       [{"added": {}}] 10      1
4       2025-04-11 22:33:37.363545+00   3       Class object (3)        1       [{"added": {}}] 10      1
5       2025-04-11 22:33:42.442461+00   4       Class object (4)        1       [{"added": {}}] 10      1
6       2025-04-11 22:33:52.816168+00   5       Class object (5)        1       [{"added": {}}] 10      1
7       2025-04-11 22:36:39.972334+00   1       Characterization        1       [{"added": {}}] 6       1
8       2025-04-11 22:36:47.530908+00   2       Durability      1       [{"added": {}}] 6       1
9       2025-04-11 22:37:21.194186+00   3       Performance     1       [{"added": {}}] 6       1
10      2025-04-11 23:48:06.5572+00     4       Impedance       1       [{"added": {}}] 6       1
11      2025-04-11 23:48:18.312019+00   5       Potentiostatic  1       [{"added": {}}] 6       1
12      2025-04-11 23:48:31.027461+00   6       Pulse Width Modulation  1       [{"added": {}}] 6       1
13      2025-04-11 23:49:10.077543+00   7       5-11-22-5A      1       [{"added": {}}] 6       1
14      2025-04-11 23:49:26.020806+00   8       BC-7    1       [{"added": {}}] 6       1
15      2025-04-11 23:49:32.961453+00   9       BC-8    1       [{"added": {}}] 6       1
16      2025-04-11 23:49:39.719296+00   10      BC-9    1       [{"added": {}}] 6       1
17      2025-04-11 23:49:51.455773+00   11      BC-12   1       [{"added": {}}] 6       1
18      2025-04-11 23:50:04.419645+00   12      BC-15   1       [{"added": {}}] 6       1
19      2025-04-11 23:50:10.563086+00   13      BC-16   1       [{"added": {}}] 6       1
20      2025-04-11 23:51:45.27818+00    14      2-4-22-2A       1       [{"added": {}}] 6       1
21      2025-04-11 23:52:05.099414+00   15      BC-18   1       [{"added": {}}] 6       1
22      2025-04-11 23:52:10.927215+00   16      BC-33   1       [{"added": {}}] 6       1
23      2025-04-11 23:52:40.970529+00   17      1-14-22-3A      1       [{"added": {}}] 6       1
24      2025-04-11 23:52:54.099528+00   18      4-12-22-2A      1       [{"added": {}}] 6       1
25      2025-04-11 23:53:04.199452+00   19      5-11-22-2A      1       [{"added": {}}] 6       1
26      2025-04-11 23:53:41.488783+00   20      BC-10   1       [{"added": {}}] 6       1
27      2025-04-11 23:54:06.281778+00   21      BC-3    1       [{"added": {}}] 6       1
28      2025-04-11 23:54:36.46627+00    22      BC-2    1       [{"added": {}}] 6       1
29      2025-04-11 23:54:43.094034+00   23      BC-6    1       [{"added": {}}] 6       1
30      2025-04-11 23:54:53.770211+00   24      BC-20   1       [{"added": {}}] 6       1
31      2025-04-11 23:54:59.466501+00   25      BC-34   1       [{"added": {}}] 6       1
32      2025-04-11 23:55:07.17664+00    26      BC-36   1       [{"added": {}}] 6       1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1       admin   logentry
2       auth    permission
3       auth    group
4       auth    user
5       warehouse       ontology
6       warehouse       node
7       warehouse       relationship
8       contenttypes    contenttype
9       sessions        session
10      warehouse       class
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1       contenttypes    0001_initial    2025-04-11 22:28:43.70929+00
2       auth    0001_initial    2025-04-11 22:28:43.746545+00
3       admin   0001_initial    2025-04-11 22:28:43.76064+00
4       admin   0002_logentry_remove_auto_add   2025-04-11 22:28:43.765987+00
5       admin   0003_logentry_add_action_flag_choices   2025-04-11 22:28:43.772877+00
6       contenttypes    0002_remove_content_type_name   2025-04-11 22:28:43.786025+00
7       auth    0002_alter_permission_name_max_length   2025-04-11 22:28:43.793166+00
8       auth    0003_alter_user_email_max_length        2025-04-11 22:28:43.801127+00
9       auth    0004_alter_user_username_opts   2025-04-11 22:28:43.80694+00
10      auth    0005_alter_user_last_login_null 2025-04-11 22:28:43.815295+00
11      auth    0006_require_contenttypes_0002  2025-04-11 22:28:43.817912+00
12      auth    0007_alter_validators_add_error_messages        2025-04-11 22:28:43.823709+00
13      auth    0008_alter_user_username_max_length     2025-04-11 22:28:43.831892+00
14      auth    0009_alter_user_last_name_max_length    2025-04-11 22:28:43.838727+00
15      auth    0010_alter_group_name_max_length        2025-04-11 22:28:43.847737+00
16      auth    0011_update_proxy_permissions   2025-04-11 22:28:43.852946+00
17      auth    0012_alter_user_first_name_max_length   2025-04-11 22:28:43.86118+00
18      sessions        0001_initial    2025-04-11 22:28:43.869383+00
19      warehouse       0001_initial    2025-04-11 22:28:43.891622+00
20      warehouse       0002_class_alter_node_cls       2025-04-11 22:31:34.211442+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
xxc8a9hu4k86t18b8p28o3tb5upjz371        .eJxVjEEOwiAQRe_C2hBmhhJw6d4zkGEAqZo2Ke3KeHdt0oVu_3vvv1TkbW1x62WJY1ZnBer0uyWWR5l2kO883WYt87QuY9K7og_a9XXO5Xk53L-Dxr1964peCKznFCyBiGFKpkJCwmLJ54AAQ_YyQAAsBCgJC2fnnbGVnKj3B9AMN1E:1u3MsH:zkubcqEo0K-GgYHgmaKacicpqh7n_fW7-YlX0LtMDnE   2025-04-25 22:29:25.463305+00
\.


--
-- Data for Name: warehouse_class; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.warehouse_class (id, name, description) FROM stdin;
1       Category        test category
2       Type    test type
3       Batch   electrolysis cell batch
4       Cell    electrolysis cell
5       Stack   electrolysis cell stack
\.


--
-- Data for Name: warehouse_node; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.warehouse_node (id, name, cls_id, ontology_id) FROM stdin;
1       Characterization        1       1
2       Durability      1       1
3       Performance     1       1
4       Impedance       2       1
5       Potentiostatic  2       1
6       Pulse Width Modulation  2       1
7       5-11-22-5A      3       1
8       BC-7    4       1
9       BC-8    4       1
10      BC-9    4       1
11      BC-12   4       1
12      BC-15   4       1
13      BC-16   4       1
14      2-4-22-2A       3       1
15      BC-18   4       1
16      BC-33   4       1
17      1-14-22-3A      3       1
18      4-12-22-2A      3       1
19      5-11-22-2A      3       1
20      BC-10   4       1
21      BC-3    4       1
22      BC-2    4       1
23      BC-6    4       1
24      BC-20   4       1
25      BC-34   4       1
26      BC-36   4       1
\.


--
-- Data for Name: warehouse_ontology; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.warehouse_ontology (id, name) FROM stdin;
1       H2NEW
\.


--
-- Data for Name: warehouse_relationship; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.warehouse_relationship (id, name, ontology_id, source_id, target_id) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 40, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 32, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 10, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 20, true);


--
-- Name: warehouse_class_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.warehouse_class_id_seq', 5, true);


--
-- Name: warehouse_node_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.warehouse_node_id_seq', 26, true);


--
-- Name: warehouse_ontology_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.warehouse_ontology_id_seq', 1, true);


--
-- Name: warehouse_relationship_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.warehouse_relationship_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: warehouse_class warehouse_class_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.warehouse_class
    ADD CONSTRAINT warehouse_class_name_key UNIQUE (name);


--
-- Name: warehouse_class warehouse_class_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.warehouse_class
    ADD CONSTRAINT warehouse_class_pkey PRIMARY KEY (id);


--
-- Name: warehouse_node warehouse_node_name_cls_ontology_id_ae2cb8f8_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.warehouse_node
    ADD CONSTRAINT warehouse_node_name_cls_ontology_id_ae2cb8f8_uniq UNIQUE (name, cls_id, ontology_id);


--
-- Name: warehouse_node warehouse_node_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.warehouse_node
    ADD CONSTRAINT warehouse_node_pkey PRIMARY KEY (id);


--
-- Name: warehouse_ontology warehouse_ontology_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.warehouse_ontology
    ADD CONSTRAINT warehouse_ontology_name_key UNIQUE (name);


--
-- Name: warehouse_ontology warehouse_ontology_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.warehouse_ontology
    ADD CONSTRAINT warehouse_ontology_pkey PRIMARY KEY (id);


--
-- Name: warehouse_relationship warehouse_relationship_name_source_id_target_id_ab4b3081_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.warehouse_relationship
    ADD CONSTRAINT warehouse_relationship_name_source_id_target_id_ab4b3081_uniq UNIQUE (name, source_id, target_id, ontology_id);


--
-- Name: warehouse_relationship warehouse_relationship_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.warehouse_relationship
    ADD CONSTRAINT warehouse_relationship_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: warehouse_class_name_c7b146ea_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX warehouse_class_name_c7b146ea_like ON public.warehouse_class USING btree (name varchar_pattern_ops);


--
-- Name: warehouse_node_cls_id_d0d0c0fc; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX warehouse_node_cls_id_d0d0c0fc ON public.warehouse_node USING btree (cls_id);


--
-- Name: warehouse_node_ontology_id_7255ec94; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX warehouse_node_ontology_id_7255ec94 ON public.warehouse_node USING btree (ontology_id);


--
-- Name: warehouse_ontology_name_be1705ea_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX warehouse_ontology_name_be1705ea_like ON public.warehouse_ontology USING btree (name varchar_pattern_ops);


--
-- Name: warehouse_relationship_ontology_id_b677834d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX warehouse_relationship_ontology_id_b677834d ON public.warehouse_relationship USING btree (ontology_id);


--
-- Name: warehouse_relationship_source_id_ce230b32; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX warehouse_relationship_source_id_ce230b32 ON public.warehouse_relationship USING btree (source_id);


--
-- Name: warehouse_relationship_target_id_be147a02; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX warehouse_relationship_target_id_be147a02 ON public.warehouse_relationship USING btree (target_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: warehouse_node warehouse_node_cls_id_d0d0c0fc_fk_warehouse_class_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.warehouse_node
    ADD CONSTRAINT warehouse_node_cls_id_d0d0c0fc_fk_warehouse_class_id FOREIGN KEY (cls_id) REFERENCES public.warehouse_class(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: warehouse_node warehouse_node_ontology_id_7255ec94_fk_warehouse_ontology_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.warehouse_node
    ADD CONSTRAINT warehouse_node_ontology_id_7255ec94_fk_warehouse_ontology_id FOREIGN KEY (ontology_id) REFERENCES public.warehouse_ontology(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: warehouse_relationship warehouse_relationsh_ontology_id_b677834d_fk_warehouse; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.warehouse_relationship
    ADD CONSTRAINT warehouse_relationsh_ontology_id_b677834d_fk_warehouse FOREIGN KEY (ontology_id) REFERENCES public.warehouse_ontology(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: warehouse_relationship warehouse_relationship_source_id_ce230b32_fk_warehouse_node_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.warehouse_relationship
    ADD CONSTRAINT warehouse_relationship_source_id_ce230b32_fk_warehouse_node_id FOREIGN KEY (source_id) REFERENCES public.warehouse_node(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: warehouse_relationship warehouse_relationship_target_id_be147a02_fk_warehouse_node_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.warehouse_relationship
    ADD CONSTRAINT warehouse_relationship_target_id_be147a02_fk_warehouse_node_id FOREIGN KEY (target_id) REFERENCES public.warehouse_node(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--