# Generated by Django 5.2 on 2025-04-11 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ontology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'verbose_name': 'ontology',
                'verbose_name_plural': 'Ontologies',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('cls', models.CharField(max_length=25)),
                ('ontology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='warehouse.ontology')),
            ],
            options={
                'unique_together': {('name', 'cls', 'ontology')},
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('ontology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='warehouse.ontology')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='warehouse.node')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='warehouse.node')),
            ],
            options={
                'unique_together': {('name', 'source', 'target', 'ontology')},
            },
        ),
    ]
