# Generated by Django 5.2 on 2025-04-16 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('description', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'class',
                'verbose_name_plural': 'classes',
            },
        ),
        migrations.CreateModel(
            name='Ontology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'verbose_name': 'ontology',
                'verbose_name_plural': 'ontologies',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('root', models.BooleanField(default=False)),
                ('cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='warehouse.class')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='warehouse.node')),
                ('ontology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='warehouse.ontology')),
            ],
            options={
                'unique_together': {('name', 'cls', 'parent', 'ontology')},
            },
        ),
        migrations.AddField(
            model_name='class',
            name='ontology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='warehouse.ontology'),
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ontology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='warehouse.ontology')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='warehouse.node')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='warehouse.node')),
            ],
            options={
                'unique_together': {('source', 'target', 'ontology')},
            },
        ),
    ]
