# Generated by Django 5.2 on 2025-05-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='root',
            field=models.BooleanField(default=False, help_text='Imporant: Faraday nodes are roots only if their cls is a Category'),
        ),
    ]
