# Generated by Django 5.2 on 2025-04-18 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='node',
            unique_together={('name', 'cls', 'ontology')},
        ),
        migrations.RemoveField(
            model_name='node',
            name='parent',
        ),
    ]
