# Generated by Django 5.2 on 2025-04-12 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_class_alter_node_cls'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'class', 'verbose_name_plural': 'classes'},
        ),
        migrations.AlterModelOptions(
            name='ontology',
            options={'verbose_name': 'ontology', 'verbose_name_plural': 'ontologies'},
        ),
        migrations.AddField(
            model_name='class',
            name='ontology',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='warehouse.ontology'),
            preserve_default=False,
        ),
    ]
