# Generated by Django 5.2 on 2025-04-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_class_options_alter_ontology_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='root',
            field=models.BooleanField(default=False),
        ),
    ]
