# Generated by Django 5.2 on 2025-04-12 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_node_root'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='warehouse.node'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='warehouse.node'),
        ),
    ]
