# Generated by Django 5.2 on 2025-04-14 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_alter_relationship_source_alter_relationship_target'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('source', 'target', 'ontology')},
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='name',
        ),
    ]
